runtime: python
env: flex

entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static
- url: .*
  script: auto

